export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_PLAYLISTS:"SET_PLAYLISTS",
    SET_USER:"SET_USER",
    SET_PLAYLIST:"SET_PLAYLIST",
    SET_PLAYLIST_Id:"SET_PLAYLIST_Id",
    SET_PLAYER_STATE:"SET_PLAYER_STATE",
    CURRENTLY_PLAYING:"CURRENTLY_PLAYING",
}